// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('interstella', []).controller('interstellaController', function($scope, $interval) {
    $scope.lastNames = [];
    $scope.nextNames = [];
    $scope.team = $scope.currentNames = ["asl", "eyoung", "pmumma", "lbrown", "jpincar", "avolkovitsky", "krichert", "jhancock", "kstewart", "jstoecker", "estrom", "dryan", "jdhague", "dcameron", "iharlow", "mlooney"];
    $scope.pollAudio = function() {
      var now;
      now = $("#audio")[0].currentTime;
      console.log(now);
      console.log($scope.timings[$scope.currentTimingIndex].time);
      if ($scope.timings[$scope.currentTimingIndex + 1] && $scope.timings[$scope.currentTimingIndex + 1].time < now) {
        $scope.currentTimingIndex += 1;
        return $scope.doTransition();
      }
    };
    $scope.doTransition = function() {
      console.log("Transform");
      $scope.lastNames = $scope.currentNames;
      $scope.currentNames = $scope.timings[$scope.currentTimingIndex].names;
      if ($scope.timings[$scope.currentTimingIndex + 1]) {
        $scope.nextNames = $scope.timings[$scope.currentTimingIndex + 1].names;
      }
      $.each($scope.lastNames, function(index, name) {
        $("#" + name).removeClass();
        return $("#" + name).addClass("last");
      });
      $.each($scope.currentNames, function(index, name) {
        $("#" + name).removeClass();
        return $("#" + name).addClass("current");
      });
      return $.each($scope.nextNames, function(index, name) {
        $("#" + name).removeClass();
        return $("#" + name).addClass("next");
      });
    };
    $scope.nameFilter = function(member) {
      return $scope.currentNames.indexOf(member.name) !== -1;
    };
    $scope.timings = [];
    $scope.currentTimingIndex = 0;
    return $.get('timings.txt', function(data) {
      var lines;
      lines = data.split("\n");
      console.log(lines);
      return $.each(lines, function(n, elem) {
        var i, time;
        console.log(elem);
        if (elem) {
          i = elem.indexOf(',');
          time = elem.slice(0, i);
          $scope.timings.push({
            time: parseFloat(time),
            names: JSON.parse(elem.slice(i + 1))
          });
          return $interval($scope.pollAudio, 500, 100);
        }
      });
    });
  });

}).call(this);
